spring:
  application:
    name: notification

  datasource:
    url: jdbc:mysql://mysql_db:3306/notification_db?createDatabaseIfNotExist=true
    username: root
    password: root@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

  kafka:
    bootstrap-servers: kafka-1:9092

    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

    listener:
      ack-mode: RECORD
      concurrency: 3
      missing-topics-fatal: false

server:
  port: 8084

notification:
  message: "Welcome to the Notification Service!"
  apikey: "api_key_98765"


logging:
  level:
    org.apache.kafka: INFO
    org.springframework.kafka: INFO
