spring:
  application:
    name: shipping

  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: jdbc:mysql://localhost:3306/shipping_db?createDatabaseIfNotExist=true
    username: root
    password: root@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

server:
  port: 8088

shipping:
  message: Welcome to the Shipping Service!
  apikey: api_key_11223